# main text of home
name: tobeyouth
bio: A Man

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpeg

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: https://www.linkedin.com/in/%E5%AD%A3-%E6%A5%A0-66702652/


url: https://tobeyouth.github.io


# social
instagram: tobeyouth_
facebook: to.beyouth.5
twitter: tobeyouth
github: tobeyouth
email: tobeyouth@gmail.com

# normal = 560px / large = 810px
width: normal

projects: true
about: true
blog: true
read-time: true
show-tags: true
related: true
post-advance-links: [blog]
show-author: true
animation: true


gems:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji

jekyll-mentions:
    base_url: https://github.com

markdown: kramdown
permalink: pretty
highlighter: rouge
